name: Publish Release

on:
  release:
    types: [published]

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version-file: .tool-versions

      - run: bun i --frozen-lockfile
      - run: bun run zip -b chrome

      - run: bun run submit --edge-zip .output/*-chrome.zip
        env:
          EDGE_PRODUCT_ID: ${{ secrets.EDGE_PRODUCT_ID }}
          EDGE_CLIENT_ID: ${{ secrets.EDGE_CLIENT_ID }}
          EDGE_API_KEY: ${{ secrets.EDGE_API_KEY }}

      - uses: csexton/release-asset-action@3567794e918fa3068116688122a76cdeb57b5f09 # v3
        with:
          pattern: .output/*.zip
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ github.event.release.upload_url }}

      - uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2
        with:
          subject-path: .output/*.zip
          subject-name: SE Review Helper ${{ github.event.release.tag_name }}
